# Generated by Django 5.0.6 on 2024-05-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_favorites_favoritearticles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='', null=True, upload_to='blog_imgs'),
        ),
    ]
