# Generated by Django 5.0.6 on 2024-05-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_myuser_country_myuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='speciality',
            field=models.CharField(blank=True, max_length=1000000, null=True, verbose_name='Speciality'),
        ),
    ]
