# Generated by Django 5.0.6 on 2024-05-26 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_article_last_updated_hiddenquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
