# Generated by Django 5.0.6 on 2024-05-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='purchased_on',
        ),
        migrations.AddField(
            model_name='membership',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
